name: Akismet
version: "1.8"
description: Provides Akismet spam filter for form submissions
url: https://github.com/edalzell/statamic-akismet
developer: Erin Dalzell
developer_url: https://silentzconsulting.com/
commercial: true