fields:
  akismet_key:
    type: text
    validate: required
  roles:
    type: user_roles
    instructions: Add roles that are allowed to access the Spam Queue
  user_fields:
    type: section
  user_check_registrations:
    type: toggle
    display: Check User Registrations?
    default: false
    width: 25
  user_first_name_field:
    type: suggest
    mode: akismet.user_fields
    display: First Name Field
    max_items: 1
    width: 25
    show_when:
      user_check_registrations: true
  user_last_name_field:
    type: suggest
    mode: akismet.user_fields
    display: Last Name Field
    max_items: 1
    width: 25
    show_when:
      user_check_registrations: true
  user_content_field:
    type: suggest
    mode: akismet.user_fields
    display: Content Field
    max_items: 1
    width: 25
    show_when:
      user_check_registrations: true
  form_fields_section:
    type: section
    display: Forms & Fields
  forms:
    type: grid
    display: " "
    fields:
      form_and_fields:
        type: akismet
        display: "Form & Fields"
        instructions: "Please add one row at a time, saving each time (there's an issue)"
        validate: required
    mode: table
    min_rows: "1"
    add_row: Add Form
